server:
  port: 8086

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3307/Microservices
    username: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: test

  config:
    import: "configserver:http://localhost:8092"
